default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: world_pets_development

test:
  <<: *default
  database: world_pets_test

production:
  <<: *default
  database: world_pets_production
  username: world_pets
  password: <%= ENV["WORLD_PETS_DATABASE_PASSWORD"] %>
